// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScrapper.Data;

namespace WebScrapper.Data.Migrations
{
    [DbContext(typeof(BreedDbContext))]
    partial class BreedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebScrapper.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LifeSpan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("WebScrapper.Models.Traits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Adaptability")
                        .HasColumnType("int");

                    b.Property<int>("AffectionLevel")
                        .HasColumnType("int");

                    b.Property<int>("AppartmentFriendly")
                        .HasColumnType("int");

                    b.Property<int>("BarkingTendencies")
                        .HasColumnType("int");

                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<int>("CatFriendly")
                        .HasColumnType("int");

                    b.Property<int>("ChildFriendly")
                        .HasColumnType("int");

                    b.Property<int>("DogFriendly")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseNeeds")
                        .HasColumnType("int");

                    b.Property<int>("Grooming")
                        .HasColumnType("int");

                    b.Property<int>("HealthIssues")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Playfulness")
                        .HasColumnType("int");

                    b.Property<int>("SheddingLevel")
                        .HasColumnType("int");

                    b.Property<int>("SocialNeeds")
                        .HasColumnType("int");

                    b.Property<int>("StrangerFriendly")
                        .HasColumnType("int");

                    b.Property<int>("Territorial")
                        .HasColumnType("int");

                    b.Property<int>("Trainability")
                        .HasColumnType("int");

                    b.Property<int>("WatchdogAbility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("WebScrapper.Models.Traits", b =>
                {
                    b.HasOne("WebScrapper.Models.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
